import type { Locale } from "@/i18n/config";

// Canonical topic keys. The English key doubles as the English URL slug, so
// existing /en/... URLs stay unchanged.
export const topics = [
  "protein-for-weight-loss",
  "protein-for-muscle-gain",
  "protein-for-women",
  "protein-on-ozempic-wegovy",
  "high-protein-foods",
  "protein-by-body-weight",
  "vegetarian-vegan-protein",
  "protein-for-men",
  "protein-for-seniors",
  "protein-for-teenagers",
  "protein-during-pregnancy",
  "best-time-to-eat-protein",
  "protein-shakes-per-day",
  "protein-for-diabetics",
  "protein-deficiency-signs",
  "protein-for-athletes",
  "protein-for-runners",
  "protein-for-bodybuilding",
  "protein-for-endurance",
  "protein-for-cyclists",
  "protein-for-swimmers",
  "protein-for-crossfit",
  "protein-for-strength-training",
  "protein-for-calisthenics",
  "protein-for-marathon-training",
  "protein-for-cutting",
  "protein-for-bulking",
  "protein-for-body-recomposition",
  "protein-for-lean-bulk",
  "protein-for-fat-loss",
  "protein-for-maintaining-muscle",
  "protein-for-beginners",
  "protein-for-home-workouts",
  "protein-per-meal",
  "protein-before-bed",
  "protein-after-workout",
  "protein-before-workout",
  "protein-for-breakfast",
  "protein-for-recovery",
  "protein-for-keto-diet",
  "protein-for-intermittent-fasting",
  "protein-for-weight-gain",
  "protein-for-skinny-guys",
  "protein-for-over-40",
  "protein-for-over-50",
  "protein-for-menopause",
  "protein-for-pcos",
  "protein-for-breastfeeding",
  "protein-for-postpartum",
  "protein-for-kids",
  "protein-for-toddlers",
  "protein-for-hair-growth",
  "protein-for-skin",
  "protein-for-wound-healing",
  "protein-for-sarcopenia",
  "whey-vs-plant-protein",
  "protein-grams-per-pound",
  "how-much-protein-to-build-muscle",
  "how-much-protein-per-day",
  "protein-for-two-meals-a-day",
  "protein-for-office-workers",
  "protein-for-hiking",
  "protein-for-soccer-players",
  "protein-for-basketball-players",
  "protein-for-gym-beginners",
] as const;

export type TopicKey = (typeof topics)[number];

// Topics whose page copy lives in the dictionaries' `topicPages.items` section
// (rendered by a generic paragraphs + bullets layout) rather than in a
// hand-built section of the topic page.
export const contentTopics = [
  "protein-for-men",
  "protein-for-seniors",
  "protein-for-teenagers",
  "protein-during-pregnancy",
  "best-time-to-eat-protein",
  "protein-shakes-per-day",
  "protein-for-diabetics",
  "protein-deficiency-signs",
  "protein-for-athletes",
  "protein-for-runners",
  "protein-for-bodybuilding",
  "protein-for-endurance",
  "protein-for-cyclists",
  "protein-for-swimmers",
  "protein-for-crossfit",
  "protein-for-strength-training",
  "protein-for-calisthenics",
  "protein-for-marathon-training",
  "protein-for-cutting",
  "protein-for-bulking",
  "protein-for-body-recomposition",
  "protein-for-lean-bulk",
  "protein-for-fat-loss",
  "protein-for-maintaining-muscle",
  "protein-for-beginners",
  "protein-for-home-workouts",
  "protein-per-meal",
  "protein-before-bed",
  "protein-after-workout",
  "protein-before-workout",
  "protein-for-breakfast",
  "protein-for-recovery",
  "protein-for-keto-diet",
  "protein-for-intermittent-fasting",
  "protein-for-weight-gain",
  "protein-for-skinny-guys",
  "protein-for-over-40",
  "protein-for-over-50",
  "protein-for-menopause",
  "protein-for-pcos",
  "protein-for-breastfeeding",
  "protein-for-postpartum",
  "protein-for-kids",
  "protein-for-toddlers",
  "protein-for-hair-growth",
  "protein-for-skin",
  "protein-for-wound-healing",
  "protein-for-sarcopenia",
  "whey-vs-plant-protein",
  "protein-grams-per-pound",
  "how-much-protein-to-build-muscle",
  "how-much-protein-per-day",
  "protein-for-two-meals-a-day",
  "protein-for-office-workers",
  "protein-for-hiking",
  "protein-for-soccer-players",
  "protein-for-basketball-players",
  "protein-for-gym-beginners",
] as const;

export type ContentTopicKey = (typeof contentTopics)[number];

export function isContentTopic(topic: TopicKey): topic is ContentTopicKey {
  return (contentTopics as readonly string[]).includes(topic);
}

// URL slug for each topic in each locale, so every language ranks on its own
// keyword. Latin-script slugs are ASCII-folded (no accents/umlauts) to keep
// URLs clean. Arabic reuses the English slug to avoid percent-encoded URLs.
export const topicSlugs: Record<Locale, Record<TopicKey, string>> = {
  en: {
    "protein-for-weight-loss": "protein-for-weight-loss",
    "protein-for-muscle-gain": "protein-for-muscle-gain",
    "protein-for-women": "protein-for-women",
    "protein-on-ozempic-wegovy": "protein-on-ozempic-wegovy",
    "high-protein-foods": "high-protein-foods",
    "protein-by-body-weight": "protein-by-body-weight",
    "vegetarian-vegan-protein": "vegetarian-vegan-protein",
    "protein-for-men": "protein-for-men",
    "protein-for-seniors": "protein-for-seniors",
    "protein-for-teenagers": "protein-for-teenagers",
    "protein-during-pregnancy": "protein-during-pregnancy",
    "best-time-to-eat-protein": "best-time-to-eat-protein",
    "protein-shakes-per-day": "protein-shakes-per-day",
    "protein-for-diabetics": "protein-for-diabetics",
    "protein-deficiency-signs": "protein-deficiency-signs",
    "protein-for-athletes": "protein-for-athletes",
    "protein-for-runners": "protein-for-runners",
    "protein-for-bodybuilding": "protein-for-bodybuilding",
    "protein-for-endurance": "protein-for-endurance",
    "protein-for-cyclists": "protein-for-cyclists",
    "protein-for-swimmers": "protein-for-swimmers",
    "protein-for-crossfit": "protein-for-crossfit",
    "protein-for-strength-training": "protein-for-strength-training",
    "protein-for-calisthenics": "protein-for-calisthenics",
    "protein-for-marathon-training": "protein-for-marathon-training",
    "protein-for-cutting": "protein-for-cutting",
    "protein-for-bulking": "protein-for-bulking",
    "protein-for-body-recomposition": "protein-for-body-recomposition",
    "protein-for-lean-bulk": "protein-for-lean-bulk",
    "protein-for-fat-loss": "protein-for-fat-loss",
    "protein-for-maintaining-muscle": "protein-for-maintaining-muscle",
    "protein-for-beginners": "protein-for-beginners",
    "protein-for-home-workouts": "protein-for-home-workouts",
    "protein-per-meal": "protein-per-meal",
    "protein-before-bed": "protein-before-bed",
    "protein-after-workout": "protein-after-workout",
    "protein-before-workout": "protein-before-workout",
    "protein-for-breakfast": "protein-for-breakfast",
    "protein-for-recovery": "protein-for-recovery",
    "protein-for-keto-diet": "protein-for-keto-diet",
    "protein-for-intermittent-fasting": "protein-for-intermittent-fasting",
    "protein-for-weight-gain": "protein-for-weight-gain",
    "protein-for-skinny-guys": "protein-for-skinny-guys",
    "protein-for-over-40": "protein-for-over-40",
    "protein-for-over-50": "protein-for-over-50",
    "protein-for-menopause": "protein-for-menopause",
    "protein-for-pcos": "protein-for-pcos",
    "protein-for-breastfeeding": "protein-for-breastfeeding",
    "protein-for-postpartum": "protein-for-postpartum",
    "protein-for-kids": "protein-for-kids",
    "protein-for-toddlers": "protein-for-toddlers",
    "protein-for-hair-growth": "protein-for-hair-growth",
    "protein-for-skin": "protein-for-skin",
    "protein-for-wound-healing": "protein-for-wound-healing",
    "protein-for-sarcopenia": "protein-for-sarcopenia",
    "whey-vs-plant-protein": "whey-vs-plant-protein",
    "protein-grams-per-pound": "protein-grams-per-pound",
    "how-much-protein-to-build-muscle": "how-much-protein-to-build-muscle",
    "how-much-protein-per-day": "how-much-protein-per-day",
    "protein-for-two-meals-a-day": "protein-for-two-meals-a-day",
    "protein-for-office-workers": "protein-for-office-workers",
    "protein-for-hiking": "protein-for-hiking",
    "protein-for-soccer-players": "protein-for-soccer-players",
    "protein-for-basketball-players": "protein-for-basketball-players",
    "protein-for-gym-beginners": "protein-for-gym-beginners",
  },
  es: {
    "protein-for-weight-loss": "proteina-para-perder-peso",
    "protein-for-muscle-gain": "proteina-para-ganar-musculo",
    "protein-for-women": "proteina-para-mujeres",
    "protein-on-ozempic-wegovy": "proteina-con-ozempic-wegovy",
    "high-protein-foods": "alimentos-ricos-en-proteinas",
    "protein-by-body-weight": "proteina-por-peso-corporal",
    "vegetarian-vegan-protein": "proteina-vegetariana-vegana",
    "protein-for-men": "proteina-para-hombres",
    "protein-for-seniors": "proteina-para-adultos-mayores",
    "protein-for-teenagers": "proteina-para-adolescentes",
    "protein-during-pregnancy": "proteina-en-el-embarazo",
    "best-time-to-eat-protein": "mejor-momento-para-tomar-proteina",
    "protein-shakes-per-day": "batidos-de-proteina-al-dia",
    "protein-for-diabetics": "proteina-para-diabeticos",
    "protein-deficiency-signs": "sintomas-de-falta-de-proteina",
    "protein-for-athletes": "proteina-para-atletas",
    "protein-for-runners": "proteina-para-corredores",
    "protein-for-bodybuilding": "proteina-para-culturismo",
    "protein-for-endurance": "proteina-para-resistencia",
    "protein-for-cyclists": "proteina-para-ciclistas",
    "protein-for-swimmers": "proteina-para-nadadores",
    "protein-for-crossfit": "proteina-para-crossfit",
    "protein-for-strength-training": "proteina-para-entrenamiento-de-fuerza",
    "protein-for-calisthenics": "proteina-para-calistenia",
    "protein-for-marathon-training": "proteina-para-entrenamiento-de-maraton",
    "protein-for-cutting": "proteina-para-definicion",
    "protein-for-bulking": "proteina-para-volumen",
    "protein-for-body-recomposition": "proteina-para-recomposicion-corporal",
    "protein-for-lean-bulk": "proteina-para-volumen-limpio",
    "protein-for-fat-loss": "proteina-para-perder-grasa",
    "protein-for-maintaining-muscle": "proteina-para-mantener-musculo",
    "protein-for-beginners": "proteina-para-principiantes",
    "protein-for-home-workouts": "proteina-para-entrenar-en-casa",
    "protein-per-meal": "proteina-por-comida",
    "protein-before-bed": "proteina-antes-de-dormir",
    "protein-after-workout": "proteina-despues-de-entrenar",
    "protein-before-workout": "proteina-antes-de-entrenar",
    "protein-for-breakfast": "proteina-en-el-desayuno",
    "protein-for-recovery": "proteina-para-la-recuperacion",
    "protein-for-keto-diet": "proteina-en-la-dieta-keto",
    "protein-for-intermittent-fasting": "proteina-en-el-ayuno-intermitente",
    "protein-for-weight-gain": "proteina-para-subir-de-peso",
    "protein-for-skinny-guys": "proteina-para-personas-delgadas",
    "protein-for-over-40": "proteina-despues-de-los-40",
    "protein-for-over-50": "proteina-despues-de-los-50",
    "protein-for-menopause": "proteina-en-la-menopausia",
    "protein-for-pcos": "proteina-para-el-sop",
    "protein-for-breastfeeding": "proteina-durante-la-lactancia",
    "protein-for-postpartum": "proteina-en-el-posparto",
    "protein-for-kids": "proteina-para-ninos",
    "protein-for-toddlers": "proteina-para-ninos-pequenos",
    "protein-for-hair-growth": "proteina-para-el-crecimiento-del-cabello",
    "protein-for-skin": "proteina-para-la-piel",
    "protein-for-wound-healing": "proteina-para-cicatrizar-heridas",
    "protein-for-sarcopenia": "proteina-para-la-sarcopenia",
    "whey-vs-plant-protein": "proteina-de-suero-vs-vegetal",
    "protein-grams-per-pound": "gramos-de-proteina-por-libra",
    "how-much-protein-to-build-muscle": "cuanta-proteina-para-ganar-musculo",
    "how-much-protein-per-day": "cuanta-proteina-al-dia",
    "protein-for-two-meals-a-day": "proteina-con-dos-comidas-al-dia",
    "protein-for-office-workers": "proteina-para-trabajos-de-oficina",
    "protein-for-hiking": "proteina-para-el-senderismo",
    "protein-for-soccer-players": "proteina-para-futbolistas",
    "protein-for-basketball-players": "proteina-para-jugadores-de-baloncesto",
    "protein-for-gym-beginners": "proteina-para-empezar-en-el-gimnasio",
  },
  fr: {
    "protein-for-weight-loss": "proteines-pour-perdre-du-poids",
    "protein-for-muscle-gain": "proteines-pour-prendre-du-muscle",
    "protein-for-women": "proteines-pour-les-femmes",
    "protein-on-ozempic-wegovy": "proteines-avec-ozempic-wegovy",
    "high-protein-foods": "aliments-riches-en-proteines",
    "protein-by-body-weight": "proteines-par-poids-corporel",
    "vegetarian-vegan-protein": "proteines-vegetariennes-veganes",
    "protein-for-men": "proteines-pour-les-hommes",
    "protein-for-seniors": "proteines-pour-les-seniors",
    "protein-for-teenagers": "proteines-pour-les-adolescents",
    "protein-during-pregnancy": "proteines-pendant-la-grossesse",
    "best-time-to-eat-protein": "meilleur-moment-pour-manger-des-proteines",
    "protein-shakes-per-day": "shakes-proteines-par-jour",
    "protein-for-diabetics": "proteines-pour-les-diabetiques",
    "protein-deficiency-signs": "symptomes-carence-en-proteines",
    "protein-for-athletes": "proteines-pour-les-athletes",
    "protein-for-runners": "proteines-pour-les-coureurs",
    "protein-for-bodybuilding": "proteines-pour-la-musculation",
    "protein-for-endurance": "proteines-pour-l-endurance",
    "protein-for-cyclists": "proteines-pour-les-cyclistes",
    "protein-for-swimmers": "proteines-pour-les-nageurs",
    "protein-for-crossfit": "proteines-pour-le-crossfit",
    "protein-for-strength-training": "proteines-pour-la-musculation-de-force",
    "protein-for-calisthenics": "proteines-pour-la-callisthenie",
    "protein-for-marathon-training": "proteines-pour-l-entrainement-marathon",
    "protein-for-cutting": "proteines-pour-la-seche",
    "protein-for-bulking": "proteines-pour-la-prise-de-masse",
    "protein-for-body-recomposition": "proteines-pour-la-recomposition-corporelle",
    "protein-for-lean-bulk": "proteines-pour-une-prise-de-masse-seche",
    "protein-for-fat-loss": "proteines-pour-perdre-de-la-graisse",
    "protein-for-maintaining-muscle": "proteines-pour-maintenir-le-muscle",
    "protein-for-beginners": "proteines-pour-les-debutants",
    "protein-for-home-workouts": "proteines-pour-l-entrainement-a-la-maison",
    "protein-per-meal": "proteines-par-repas",
    "protein-before-bed": "proteines-avant-de-dormir",
    "protein-after-workout": "proteines-apres-l-entrainement",
    "protein-before-workout": "proteines-avant-l-entrainement",
    "protein-for-breakfast": "proteines-au-petit-dejeuner",
    "protein-for-recovery": "proteines-pour-la-recuperation",
    "protein-for-keto-diet": "proteines-au-regime-keto",
    "protein-for-intermittent-fasting": "proteines-et-jeune-intermittent",
    "protein-for-weight-gain": "proteines-pour-prendre-du-poids",
    "protein-for-skinny-guys": "proteines-pour-les-personnes-maigres",
    "protein-for-over-40": "proteines-apres-40-ans",
    "protein-for-over-50": "proteines-apres-50-ans",
    "protein-for-menopause": "proteines-pendant-la-menopause",
    "protein-for-pcos": "proteines-et-sopk",
    "protein-for-breastfeeding": "proteines-pendant-l-allaitement",
    "protein-for-postpartum": "proteines-en-post-partum",
    "protein-for-kids": "proteines-pour-les-enfants",
    "protein-for-toddlers": "proteines-pour-les-tout-petits",
    "protein-for-hair-growth": "proteines-pour-la-pousse-des-cheveux",
    "protein-for-skin": "proteines-pour-la-peau",
    "protein-for-wound-healing": "proteines-pour-la-cicatrisation",
    "protein-for-sarcopenia": "proteines-contre-la-sarcopenie",
    "whey-vs-plant-protein": "proteine-de-lactoserum-vs-vegetale",
    "protein-grams-per-pound": "grammes-de-proteines-par-livre",
    "how-much-protein-to-build-muscle": "combien-de-proteines-pour-prendre-du-muscle",
    "how-much-protein-per-day": "combien-de-proteines-par-jour",
    "protein-for-two-meals-a-day": "proteines-avec-deux-repas-par-jour",
    "protein-for-office-workers": "proteines-pour-le-travail-de-bureau",
    "protein-for-hiking": "proteines-pour-la-randonnee",
    "protein-for-soccer-players": "proteines-pour-les-footballeurs",
    "protein-for-basketball-players": "proteines-pour-les-basketteurs",
    "protein-for-gym-beginners": "proteines-pour-debuter-a-la-salle",
  },
  de: {
    "protein-for-weight-loss": "protein-zum-abnehmen",
    "protein-for-muscle-gain": "protein-zum-muskelaufbau",
    "protein-for-women": "protein-fuer-frauen",
    "protein-on-ozempic-wegovy": "protein-bei-ozempic-wegovy",
    "high-protein-foods": "proteinreiche-lebensmittel",
    "protein-by-body-weight": "protein-nach-koerpergewicht",
    "vegetarian-vegan-protein": "vegetarisches-veganes-protein",
    "protein-for-men": "protein-fuer-maenner",
    "protein-for-seniors": "protein-fuer-senioren",
    "protein-for-teenagers": "protein-fuer-jugendliche",
    "protein-during-pregnancy": "protein-in-der-schwangerschaft",
    "best-time-to-eat-protein": "beste-zeit-fuer-protein",
    "protein-shakes-per-day": "proteinshakes-pro-tag",
    "protein-for-diabetics": "protein-fuer-diabetiker",
    "protein-deficiency-signs": "anzeichen-von-proteinmangel",
    "protein-for-athletes": "protein-fuer-sportler",
    "protein-for-runners": "protein-fuer-laeufer",
    "protein-for-bodybuilding": "protein-fuer-bodybuilding",
    "protein-for-endurance": "protein-fuer-ausdauersport",
    "protein-for-cyclists": "protein-fuer-radfahrer",
    "protein-for-swimmers": "protein-fuer-schwimmer",
    "protein-for-crossfit": "protein-fuer-crossfit",
    "protein-for-strength-training": "protein-fuer-krafttraining",
    "protein-for-calisthenics": "protein-fuer-calisthenics",
    "protein-for-marathon-training": "protein-fuer-marathontraining",
    "protein-for-cutting": "protein-fuer-die-definitionsphase",
    "protein-for-bulking": "protein-fuer-die-massephase",
    "protein-for-body-recomposition": "protein-fuer-die-koerperrekomposition",
    "protein-for-lean-bulk": "protein-fuer-den-lean-bulk",
    "protein-for-fat-loss": "protein-fuer-den-fettabbau",
    "protein-for-maintaining-muscle": "protein-zum-muskelerhalt",
    "protein-for-beginners": "protein-fuer-anfaenger",
    "protein-for-home-workouts": "protein-fuer-das-heimtraining",
    "protein-per-meal": "protein-pro-mahlzeit",
    "protein-before-bed": "protein-vor-dem-schlafen",
    "protein-after-workout": "protein-nach-dem-training",
    "protein-before-workout": "protein-vor-dem-training",
    "protein-for-breakfast": "protein-zum-fruehstueck",
    "protein-for-recovery": "protein-fuer-die-regeneration",
    "protein-for-keto-diet": "protein-bei-der-keto-diaet",
    "protein-for-intermittent-fasting": "protein-beim-intervallfasten",
    "protein-for-weight-gain": "protein-zum-zunehmen",
    "protein-for-skinny-guys": "protein-fuer-hardgainer",
    "protein-for-over-40": "protein-ab-40",
    "protein-for-over-50": "protein-ab-50",
    "protein-for-menopause": "protein-in-den-wechseljahren",
    "protein-for-pcos": "protein-bei-pcos",
    "protein-for-breastfeeding": "protein-in-der-stillzeit",
    "protein-for-postpartum": "protein-nach-der-geburt",
    "protein-for-kids": "protein-fuer-kinder",
    "protein-for-toddlers": "protein-fuer-kleinkinder",
    "protein-for-hair-growth": "protein-fuer-das-haarwachstum",
    "protein-for-skin": "protein-fuer-die-haut",
    "protein-for-wound-healing": "protein-fuer-die-wundheilung",
    "protein-for-sarcopenia": "protein-bei-sarkopenie",
    "whey-vs-plant-protein": "whey-vs-pflanzenprotein",
    "protein-grams-per-pound": "protein-gramm-pro-pfund",
    "how-much-protein-to-build-muscle": "wie-viel-protein-fuer-muskelaufbau",
    "how-much-protein-per-day": "wie-viel-protein-pro-tag",
    "protein-for-two-meals-a-day": "protein-bei-zwei-mahlzeiten-am-tag",
    "protein-for-office-workers": "protein-fuer-buroarbeiter",
    "protein-for-hiking": "protein-fuers-wandern",
    "protein-for-soccer-players": "protein-fuer-fussballspieler",
    "protein-for-basketball-players": "protein-fuer-basketballspieler",
    "protein-for-gym-beginners": "protein-fuer-fitnessstudio-einsteiger",
  },
  pt: {
    "protein-for-weight-loss": "proteina-para-perder-peso",
    "protein-for-muscle-gain": "proteina-para-ganhar-massa-muscular",
    "protein-for-women": "proteina-para-mulheres",
    "protein-on-ozempic-wegovy": "proteina-com-ozempic-wegovy",
    "high-protein-foods": "alimentos-ricos-em-proteina",
    "protein-by-body-weight": "proteina-por-peso-corporal",
    "vegetarian-vegan-protein": "proteina-vegetariana-vegana",
    "protein-for-men": "proteina-para-homens",
    "protein-for-seniors": "proteina-para-idosos",
    "protein-for-teenagers": "proteina-para-adolescentes",
    "protein-during-pregnancy": "proteina-na-gravidez",
    "best-time-to-eat-protein": "melhor-horario-para-comer-proteina",
    "protein-shakes-per-day": "shakes-de-proteina-por-dia",
    "protein-for-diabetics": "proteina-para-diabeticos",
    "protein-deficiency-signs": "sinais-de-falta-de-proteina",
    "protein-for-athletes": "proteina-para-atletas",
    "protein-for-runners": "proteina-para-corredores",
    "protein-for-bodybuilding": "proteina-para-musculacao",
    "protein-for-endurance": "proteina-para-resistencia",
    "protein-for-cyclists": "proteina-para-ciclistas",
    "protein-for-swimmers": "proteina-para-nadadores",
    "protein-for-crossfit": "proteina-para-crossfit",
    "protein-for-strength-training": "proteina-para-treino-de-forca",
    "protein-for-calisthenics": "proteina-para-calistenia",
    "protein-for-marathon-training": "proteina-para-treino-de-maratona",
    "protein-for-cutting": "proteina-para-definicao",
    "protein-for-bulking": "proteina-para-ganho-de-massa",
    "protein-for-body-recomposition": "proteina-para-recomposicao-corporal",
    "protein-for-lean-bulk": "proteina-para-ganho-limpo",
    "protein-for-fat-loss": "proteina-para-perder-gordura",
    "protein-for-maintaining-muscle": "proteina-para-manter-musculo",
    "protein-for-beginners": "proteina-para-iniciantes",
    "protein-for-home-workouts": "proteina-para-treino-em-casa",
    "protein-per-meal": "proteina-por-refeicao",
    "protein-before-bed": "proteina-antes-de-dormir",
    "protein-after-workout": "proteina-depois-do-treino",
    "protein-before-workout": "proteina-antes-do-treino",
    "protein-for-breakfast": "proteina-no-cafe-da-manha",
    "protein-for-recovery": "proteina-para-a-recuperacao",
    "protein-for-keto-diet": "proteina-na-dieta-keto",
    "protein-for-intermittent-fasting": "proteina-no-jejum-intermitente",
    "protein-for-weight-gain": "proteina-para-ganhar-peso",
    "protein-for-skinny-guys": "proteina-para-magros",
    "protein-for-over-40": "proteina-depois-dos-40",
    "protein-for-over-50": "proteina-depois-dos-50",
    "protein-for-menopause": "proteina-na-menopausa",
    "protein-for-pcos": "proteina-para-sop",
    "protein-for-breastfeeding": "proteina-durante-a-amamentacao",
    "protein-for-postpartum": "proteina-no-pos-parto",
    "protein-for-kids": "proteina-para-criancas",
    "protein-for-toddlers": "proteina-para-bebes",
    "protein-for-hair-growth": "proteina-para-o-crescimento-do-cabelo",
    "protein-for-skin": "proteina-para-a-pele",
    "protein-for-wound-healing": "proteina-para-cicatrizacao",
    "protein-for-sarcopenia": "proteina-para-a-sarcopenia",
    "whey-vs-plant-protein": "proteina-whey-vs-vegetal",
    "protein-grams-per-pound": "gramas-de-proteina-por-libra",
    "how-much-protein-to-build-muscle": "quanta-proteina-para-ganhar-musculo",
    "how-much-protein-per-day": "quanta-proteina-por-dia",
    "protein-for-two-meals-a-day": "proteina-com-duas-refeicoes-por-dia",
    "protein-for-office-workers": "proteina-para-trabalho-de-escritorio",
    "protein-for-hiking": "proteina-para-caminhadas",
    "protein-for-soccer-players": "proteina-para-jogadores-de-futebol",
    "protein-for-basketball-players": "proteina-para-jogadores-de-basquete",
    "protein-for-gym-beginners": "proteina-para-iniciantes-na-academia",
  },
  it: {
    "protein-for-weight-loss": "proteine-per-dimagrire",
    "protein-for-muscle-gain": "proteine-per-la-massa-muscolare",
    "protein-for-women": "proteine-per-le-donne",
    "protein-on-ozempic-wegovy": "proteine-con-ozempic-wegovy",
    "high-protein-foods": "alimenti-ricchi-di-proteine",
    "protein-by-body-weight": "proteine-per-peso-corporeo",
    "vegetarian-vegan-protein": "proteine-vegetariane-vegane",
    "protein-for-men": "proteine-per-gli-uomini",
    "protein-for-seniors": "proteine-per-anziani",
    "protein-for-teenagers": "proteine-per-adolescenti",
    "protein-during-pregnancy": "proteine-in-gravidanza",
    "best-time-to-eat-protein": "momento-migliore-per-assumere-proteine",
    "protein-shakes-per-day": "frullati-proteici-al-giorno",
    "protein-for-diabetics": "proteine-per-diabetici",
    "protein-deficiency-signs": "sintomi-di-carenza-di-proteine",
    "protein-for-athletes": "proteine-per-atleti",
    "protein-for-runners": "proteine-per-corridori",
    "protein-for-bodybuilding": "proteine-per-il-bodybuilding",
    "protein-for-endurance": "proteine-per-la-resistenza",
    "protein-for-cyclists": "proteine-per-ciclisti",
    "protein-for-swimmers": "proteine-per-nuotatori",
    "protein-for-crossfit": "proteine-per-il-crossfit",
    "protein-for-strength-training": "proteine-per-l-allenamento-di-forza",
    "protein-for-calisthenics": "proteine-per-il-calisthenics",
    "protein-for-marathon-training": "proteine-per-l-allenamento-per-la-maratona",
    "protein-for-cutting": "proteine-per-la-definizione",
    "protein-for-bulking": "proteine-per-la-massa",
    "protein-for-body-recomposition": "proteine-per-la-ricomposizione-corporea",
    "protein-for-lean-bulk": "proteine-per-la-massa-pulita",
    "protein-for-fat-loss": "proteine-per-perdere-grasso",
    "protein-for-maintaining-muscle": "proteine-per-mantenere-il-muscolo",
    "protein-for-beginners": "proteine-per-principianti",
    "protein-for-home-workouts": "proteine-per-l-allenamento-a-casa",
    "protein-per-meal": "proteine-per-pasto",
    "protein-before-bed": "proteine-prima-di-dormire",
    "protein-after-workout": "proteine-dopo-l-allenamento",
    "protein-before-workout": "proteine-prima-dell-allenamento",
    "protein-for-breakfast": "proteine-a-colazione",
    "protein-for-recovery": "proteine-per-il-recupero",
    "protein-for-keto-diet": "proteine-nella-dieta-keto",
    "protein-for-intermittent-fasting": "proteine-e-digiuno-intermittente",
    "protein-for-weight-gain": "proteine-per-aumentare-di-peso",
    "protein-for-skinny-guys": "proteine-per-i-magri",
    "protein-for-over-40": "proteine-dopo-i-40-anni",
    "protein-for-over-50": "proteine-dopo-i-50-anni",
    "protein-for-menopause": "proteine-in-menopausa",
    "protein-for-pcos": "proteine-e-pcos",
    "protein-for-breastfeeding": "proteine-durante-l-allattamento",
    "protein-for-postpartum": "proteine-nel-post-parto",
    "protein-for-kids": "proteine-per-bambini",
    "protein-for-toddlers": "proteine-per-i-bambini-piccoli",
    "protein-for-hair-growth": "proteine-per-la-crescita-dei-capelli",
    "protein-for-skin": "proteine-per-la-pelle",
    "protein-for-wound-healing": "proteine-per-la-guarigione-delle-ferite",
    "protein-for-sarcopenia": "proteine-per-la-sarcopenia",
    "whey-vs-plant-protein": "proteine-del-siero-vs-vegetali",
    "protein-grams-per-pound": "grammi-di-proteine-per-libbra",
    "how-much-protein-to-build-muscle": "quante-proteine-per-mettere-massa",
    "how-much-protein-per-day": "quante-proteine-al-giorno",
    "protein-for-two-meals-a-day": "proteine-con-due-pasti-al-giorno",
    "protein-for-office-workers": "proteine-per-il-lavoro-d-ufficio",
    "protein-for-hiking": "proteine-per-l-escursionismo",
    "protein-for-soccer-players": "proteine-per-i-calciatori",
    "protein-for-basketball-players": "proteine-per-i-cestisti",
    "protein-for-gym-beginners": "proteine-per-chi-inizia-in-palestra",
  },
  nl: {
    "protein-for-weight-loss": "eiwit-voor-gewichtsverlies",
    "protein-for-muscle-gain": "eiwit-voor-spieropbouw",
    "protein-for-women": "eiwit-voor-vrouwen",
    "protein-on-ozempic-wegovy": "eiwit-bij-ozempic-wegovy",
    "high-protein-foods": "eiwitrijke-voeding",
    "protein-by-body-weight": "eiwit-per-lichaamsgewicht",
    "vegetarian-vegan-protein": "vegetarisch-veganistisch-eiwit",
    "protein-for-men": "eiwit-voor-mannen",
    "protein-for-seniors": "eiwit-voor-ouderen",
    "protein-for-teenagers": "eiwit-voor-tieners",
    "protein-during-pregnancy": "eiwit-tijdens-zwangerschap",
    "best-time-to-eat-protein": "beste-moment-voor-eiwitten",
    "protein-shakes-per-day": "eiwitshakes-per-dag",
    "protein-for-diabetics": "eiwit-voor-diabetici",
    "protein-deficiency-signs": "symptomen-eiwittekort",
    "protein-for-athletes": "eiwit-voor-atleten",
    "protein-for-runners": "eiwit-voor-hardlopers",
    "protein-for-bodybuilding": "eiwit-voor-bodybuilding",
    "protein-for-endurance": "eiwit-voor-uithoudingsvermogen",
    "protein-for-cyclists": "eiwit-voor-wielrenners",
    "protein-for-swimmers": "eiwit-voor-zwemmers",
    "protein-for-crossfit": "eiwit-voor-crossfit",
    "protein-for-strength-training": "eiwit-voor-krachttraining",
    "protein-for-calisthenics": "eiwit-voor-calisthenics",
    "protein-for-marathon-training": "eiwit-voor-marathontraining",
    "protein-for-cutting": "eiwit-voor-de-cut",
    "protein-for-bulking": "eiwit-voor-de-bulk",
    "protein-for-body-recomposition": "eiwit-voor-lichaamsrecompositie",
    "protein-for-lean-bulk": "eiwit-voor-lean-bulk",
    "protein-for-fat-loss": "eiwit-voor-vetverlies",
    "protein-for-maintaining-muscle": "eiwit-voor-spierbehoud",
    "protein-for-beginners": "eiwit-voor-beginners",
    "protein-for-home-workouts": "eiwit-voor-thuis-trainen",
    "protein-per-meal": "eiwit-per-maaltijd",
    "protein-before-bed": "eiwit-voor-het-slapen",
    "protein-after-workout": "eiwit-na-het-sporten",
    "protein-before-workout": "eiwit-voor-het-sporten",
    "protein-for-breakfast": "eiwit-bij-het-ontbijt",
    "protein-for-recovery": "eiwit-voor-herstel",
    "protein-for-keto-diet": "eiwit-bij-het-keto-dieet",
    "protein-for-intermittent-fasting": "eiwit-bij-intermittent-fasting",
    "protein-for-weight-gain": "eiwit-om-aan-te-komen",
    "protein-for-skinny-guys": "eiwit-voor-slanke-mensen",
    "protein-for-over-40": "eiwit-na-je-40e",
    "protein-for-over-50": "eiwit-na-je-50e",
    "protein-for-menopause": "eiwit-tijdens-de-overgang",
    "protein-for-pcos": "eiwit-bij-pcos",
    "protein-for-breastfeeding": "eiwit-tijdens-borstvoeding",
    "protein-for-postpartum": "eiwit-na-de-bevalling",
    "protein-for-kids": "eiwit-voor-kinderen",
    "protein-for-toddlers": "eiwit-voor-peuters",
    "protein-for-hair-growth": "eiwit-voor-haargroei",
    "protein-for-skin": "eiwit-voor-de-huid",
    "protein-for-wound-healing": "eiwit-voor-wondgenezing",
    "protein-for-sarcopenia": "eiwit-bij-sarcopenie",
    "whey-vs-plant-protein": "whey-vs-plantaardig-eiwit",
    "protein-grams-per-pound": "gram-eiwit-per-pond",
    "how-much-protein-to-build-muscle": "hoeveel-eiwit-voor-spieropbouw",
    "how-much-protein-per-day": "hoeveel-eiwit-per-dag",
    "protein-for-two-meals-a-day": "eiwit-bij-twee-maaltijden-per-dag",
    "protein-for-office-workers": "eiwit-voor-kantoorwerkers",
    "protein-for-hiking": "eiwit-voor-wandelen",
    "protein-for-soccer-players": "eiwit-voor-voetballers",
    "protein-for-basketball-players": "eiwit-voor-basketballers",
    "protein-for-gym-beginners": "eiwit-voor-sportschool-beginners",
  },
  ar: {
    "protein-for-weight-loss": "protein-for-weight-loss",
    "protein-for-muscle-gain": "protein-for-muscle-gain",
    "protein-for-women": "protein-for-women",
    "protein-on-ozempic-wegovy": "protein-on-ozempic-wegovy",
    "high-protein-foods": "high-protein-foods",
    "protein-by-body-weight": "protein-by-body-weight",
    "vegetarian-vegan-protein": "vegetarian-vegan-protein",
    "protein-for-men": "protein-for-men",
    "protein-for-seniors": "protein-for-seniors",
    "protein-for-teenagers": "protein-for-teenagers",
    "protein-during-pregnancy": "protein-during-pregnancy",
    "best-time-to-eat-protein": "best-time-to-eat-protein",
    "protein-shakes-per-day": "protein-shakes-per-day",
    "protein-for-diabetics": "protein-for-diabetics",
    "protein-deficiency-signs": "protein-deficiency-signs",
    "protein-for-athletes": "protein-for-athletes",
    "protein-for-runners": "protein-for-runners",
    "protein-for-bodybuilding": "protein-for-bodybuilding",
    "protein-for-endurance": "protein-for-endurance",
    "protein-for-cyclists": "protein-for-cyclists",
    "protein-for-swimmers": "protein-for-swimmers",
    "protein-for-crossfit": "protein-for-crossfit",
    "protein-for-strength-training": "protein-for-strength-training",
    "protein-for-calisthenics": "protein-for-calisthenics",
    "protein-for-marathon-training": "protein-for-marathon-training",
    "protein-for-cutting": "protein-for-cutting",
    "protein-for-bulking": "protein-for-bulking",
    "protein-for-body-recomposition": "protein-for-body-recomposition",
    "protein-for-lean-bulk": "protein-for-lean-bulk",
    "protein-for-fat-loss": "protein-for-fat-loss",
    "protein-for-maintaining-muscle": "protein-for-maintaining-muscle",
    "protein-for-beginners": "protein-for-beginners",
    "protein-for-home-workouts": "protein-for-home-workouts",
    "protein-per-meal": "protein-per-meal",
    "protein-before-bed": "protein-before-bed",
    "protein-after-workout": "protein-after-workout",
    "protein-before-workout": "protein-before-workout",
    "protein-for-breakfast": "protein-for-breakfast",
    "protein-for-recovery": "protein-for-recovery",
    "protein-for-keto-diet": "protein-for-keto-diet",
    "protein-for-intermittent-fasting": "protein-for-intermittent-fasting",
    "protein-for-weight-gain": "protein-for-weight-gain",
    "protein-for-skinny-guys": "protein-for-skinny-guys",
    "protein-for-over-40": "protein-for-over-40",
    "protein-for-over-50": "protein-for-over-50",
    "protein-for-menopause": "protein-for-menopause",
    "protein-for-pcos": "protein-for-pcos",
    "protein-for-breastfeeding": "protein-for-breastfeeding",
    "protein-for-postpartum": "protein-for-postpartum",
    "protein-for-kids": "protein-for-kids",
    "protein-for-toddlers": "protein-for-toddlers",
    "protein-for-hair-growth": "protein-for-hair-growth",
    "protein-for-skin": "protein-for-skin",
    "protein-for-wound-healing": "protein-for-wound-healing",
    "protein-for-sarcopenia": "protein-for-sarcopenia",
    "whey-vs-plant-protein": "whey-vs-plant-protein",
    "protein-grams-per-pound": "protein-grams-per-pound",
    "how-much-protein-to-build-muscle": "how-much-protein-to-build-muscle",
    "how-much-protein-per-day": "how-much-protein-per-day",
    "protein-for-two-meals-a-day": "protein-for-two-meals-a-day",
    "protein-for-office-workers": "protein-for-office-workers",
    "protein-for-hiking": "protein-for-hiking",
    "protein-for-soccer-players": "protein-for-soccer-players",
    "protein-for-basketball-players": "protein-for-basketball-players",
    "protein-for-gym-beginners": "protein-for-gym-beginners",
  },
};

export function slugForTopic(locale: Locale, topic: TopicKey): string {
  return topicSlugs[locale][topic];
}

// Reverse lookup: which topic (if any) does this locale's URL slug map to?
export function topicForSlug(
  locale: Locale,
  slug: string
): TopicKey | undefined {
  const map = topicSlugs[locale];
  return topics.find((topic) => map[topic] === slug);
}
